import type { GrowthPerson } from "./model";

// Dados sintéticos para validar UX e regras sem tocar em banco/PII reais.
export const growthPeople: GrowthPerson[] = [
  {
    id: "p-001",
    name: "Ana Martins",
    municipality: "Santo Ângelo",
    chamber: "Câmara Municipal de Santo Ângelo",
    region: "Missões",
    stage: "interested",
    engagementScore: 82,
    opportunityScore: 91,
    dataQualityScore: 96,
    lastInteractionDays: 4,
    lastEventDays: 210,
    validChannels: ["email", "sms", "portal"],
    interests: ["Inteligência Artificial", "Gestão Pública"],
    portalActive: true,
    registrationAbandoned: true,
    contacted: true,
    nextAction: "Retomar inscrição do próximo seminário",
    nextActionReason: "Alta afinidade temática, interação recente e inscrição iniciada.",
  },
  {
    id: "p-002",
    name: "Carlos Moreira",
    municipality: "Cerro Largo",
    chamber: "Câmara Municipal de Cerro Largo",
    region: "Missões",
    stage: "reachable",
    engagementScore: 38,
    opportunityScore: 78,
    dataQualityScore: 88,
    lastInteractionDays: 46,
    lastEventDays: null,
    validChannels: ["email", "phone"],
    interests: ["Licitações e Contratos", "Direito Municipal"],
    portalActive: false,
    registrationAbandoned: false,
    contacted: true,
    nextAction: "Convidar para evento temático",
    nextActionReason: "Nunca participou, mas possui contato válido e interesse compatível.",
  },
  {
    id: "p-003",
    name: "Juliana Freitas",
    municipality: "Ijuí",
    chamber: "Câmara Municipal de Ijuí",
    region: "Noroeste",
    stage: "recurring",
    engagementScore: 94,
    opportunityScore: 86,
    dataQualityScore: 100,
    lastInteractionDays: 2,
    lastEventDays: 62,
    validChannels: ["email", "sms", "phone", "portal"],
    interests: ["Gestão Pública", "Captação de Recursos"],
    portalActive: true,
    registrationAbandoned: false,
    contacted: true,
    nextAction: "Convidar como participante recorrente",
    nextActionReason: "Histórico forte de presença e relacionamento recente.",
  },
  {
    id: "p-004",
    name: "Marcos Vieira",
    municipality: "São Borja",
    chamber: "Câmara Municipal de São Borja",
    region: "Fronteira Oeste",
    stage: "identified",
    engagementScore: 8,
    opportunityScore: 52,
    dataQualityScore: 54,
    lastInteractionDays: null,
    lastEventDays: null,
    validChannels: [],
    interests: [],
    portalActive: false,
    registrationAbandoned: false,
    contacted: false,
    nextAction: "Completar dados de contato",
    nextActionReason: "Vereador identificado, mas ainda sem canal válido para relacionamento.",
  },
  {
    id: "p-005",
    name: "Patrícia Lopes",
    municipality: "Santa Rosa",
    chamber: "Câmara Municipal de Santa Rosa",
    region: "Noroeste",
    stage: "inactive",
    engagementScore: 27,
    opportunityScore: 64,
    dataQualityScore: 84,
    lastInteractionDays: 418,
    lastEventDays: 510,
    validChannels: ["email", "sms"],
    interests: ["Orçamento Municipal"],
    portalActive: false,
    registrationAbandoned: false,
    contacted: true,
    nextAction: "Iniciar jornada de reativação",
    nextActionReason: "Sem interação há mais de 12 meses, mas ainda possui canais válidos.",
  },
  {
    id: "p-006",
    name: "Rafael Nunes",
    municipality: "Cruz Alta",
    chamber: "Câmara Municipal de Cruz Alta",
    region: "Alto Jacuí",
    stage: "contacted",
    engagementScore: 42,
    opportunityScore: 73,
    dataQualityScore: 91,
    lastInteractionDays: 18,
    lastEventDays: null,
    validChannels: ["email", "phone"],
    interests: ["Transparência", "Proteção de Dados"],
    portalActive: false,
    registrationAbandoned: false,
    contacted: true,
    nextAction: "Apresentar benefícios do UVERGS 360",
    nextActionReason: "Contato recente e perfil ainda sem histórico de evento.",
  },
  {
    id: "p-007",
    name: "Luciana Prado",
    municipality: "Santa Maria",
    chamber: "Câmara Municipal de Santa Maria",
    region: "Central",
    stage: "engaged",
    engagementScore: 76,
    opportunityScore: 88,
    dataQualityScore: 93,
    lastInteractionDays: 7,
    lastEventDays: 190,
    validChannels: ["email", "sms", "portal"],
    interests: ["Comunicação Institucional", "Redes Sociais"],
    portalActive: true,
    registrationAbandoned: false,
    contacted: true,
    nextAction: "Enviar convite personalizado",
    nextActionReason: "Engajamento alto e afinidade com o tema da próxima programação.",
  },
  {
    id: "p-008",
    name: "Eduardo Campos",
    municipality: "Uruguaiana",
    chamber: "Câmara Municipal de Uruguaiana",
    region: "Fronteira Oeste",
    stage: "identified",
    engagementScore: 4,
    opportunityScore: 36,
    dataQualityScore: 62,
    lastInteractionDays: null,
    lastEventDays: null,
    validChannels: ["email"],
    interests: [],
    portalActive: false,
    registrationAbandoned: false,
    contacted: false,
    nextAction: "Realizar primeiro contato institucional",
    nextActionReason: "Cadastro identificado e canal de e-mail disponível, ainda sem relacionamento.",
  },
];
