import Link from "next/link";

const agenda = [
  ["09:00", "Abertura e credenciamento", "Recepção UVERGS"],
  ["10:00", "IA aplicada à gestão pública", "Painel principal"],
  ["11:30", "Casos práticos nos municípios", "Debate"],
  ["14:00", "Oficina: como começar com segurança", "Atividade prática"],
  ["16:30", "Encerramento e próximos passos", "Networking"],
];

export default function EventoIaGestaoPublicaPage(){
  return <div className="min-h-screen bg-white text-slate-950">
    <header className="border-b border-blue-100 bg-white/90 backdrop-blur-xl sticky top-0 z-40">
      <div className="mx-auto max-w-[1400px] px-5 lg:px-10 h-16 flex items-center gap-4"><div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-blue-800 to-cyan-500 text-white flex items-center justify-center font-black shadow-md">U</div><div className="flex-1"><p className="text-sm font-black text-blue-950">UVERGS</p><p className="text-[10px] text-slate-400">Evento demonstrativo • UVERGS 360</p></div><Link href="/portal/vereador" className="rounded-xl bg-blue-50 text-blue-700 px-3 py-2 text-xs font-black">Meu UVERGS</Link></div>
    </header>

    <main>
      <section className="relative overflow-hidden bg-gradient-to-br from-[#eef7ff] via-white to-[#effff7]">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(59,130,246,.14),transparent_24%),radial-gradient(circle_at_82%_18%,rgba(16,185,129,.12),transparent_20%)]"/>
        <div className="relative mx-auto max-w-[1400px] px-5 lg:px-10 py-16 lg:py-24 grid lg:grid-cols-[1.05fr_.95fr] gap-12 items-center">
          <div><span className="inline-flex rounded-full bg-blue-700 text-white px-4 py-2 text-[10px] font-black uppercase tracking-[.18em]">24 de setembro • Porto Alegre</span><h1 className="mt-6 text-5xl lg:text-7xl font-black tracking-[-.055em] leading-[.95]">Inteligência Artificial na Gestão Pública.</h1><p className="mt-6 max-w-3xl text-xl text-slate-600 leading-relaxed">Um encontro para vereadores e lideranças municipais entenderem, na prática, onde a IA pode melhorar serviços, produtividade e tomada de decisão — com segurança e responsabilidade.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#inscricao" className="rounded-2xl bg-blue-700 px-6 py-3.5 text-sm font-black text-white shadow-xl shadow-blue-200">Quero participar</a><a href="#programacao" className="rounded-2xl border border-slate-200 bg-white px-6 py-3.5 text-sm font-black text-slate-700">Ver programação</a></div><p className="mt-5 text-xs text-slate-400">Página demonstrativa. Nenhuma inscrição real será realizada.</p></div>
          <div className="relative"><div className="rounded-[40px] bg-[#0b2554] p-8 lg:p-10 text-white shadow-2xl shadow-blue-200/60 overflow-hidden"><div className="absolute right-0 top-0 w-52 h-52 rounded-full bg-cyan-400/10 blur-3xl"/><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Por que este evento importa</p><div className="mt-7 space-y-5">{[["Decisão melhor","Entender usos reais de IA na administração e no mandato."],["Mais produtividade","Identificar tarefas que podem ser simplificadas com segurança."],["Visão prática","Sair com exemplos e próximos passos aplicáveis."],["Rede UVERGS","Trocar experiências com vereadores de diferentes regiões."]].map(([t,d],i)=><div key={t} className="flex gap-4"><div className="w-10 h-10 shrink-0 rounded-2xl bg-white/10 border border-white/10 flex items-center justify-center font-black text-cyan-300">{i+1}</div><div><p className="font-black">{t}</p><p className="mt-1 text-sm text-blue-100 leading-relaxed">{d}</p></div></div>)}</div></div></div>
        </div>
      </section>

      <section className="mx-auto max-w-[1400px] px-5 lg:px-10 py-14 grid md:grid-cols-4 gap-4">{[["1 dia","de conteúdo prático"],["5 blocos","de programação"],["Vereadores","de todo o RS"],["Certificado","digital UVERGS"]].map(([v,l])=><div key={v} className="rounded-[26px] border border-slate-200 bg-white p-6 shadow-sm"><p className="text-3xl font-black text-blue-800">{v}</p><p className="mt-2 text-sm text-slate-500">{l}</p></div>)}</section>

      <section id="programacao" className="bg-[#f6f9fe] border-y border-slate-100"><div className="mx-auto max-w-[1400px] px-5 lg:px-10 py-16"><div className="grid lg:grid-cols-[.7fr_1.3fr] gap-10"><div><p className="text-[11px] font-black uppercase tracking-[.22em] text-blue-600">Programação</p><h2 className="mt-3 text-4xl lg:text-5xl font-black tracking-tight">Conteúdo para sair com clareza, não com hype.</h2><p className="mt-4 text-slate-500 leading-relaxed">A proposta demonstrativa combina visão estratégica, exemplos de uso e orientação prática para o setor público.</p></div><div className="space-y-3">{agenda.map(([hora,titulo,tipo])=><div key={hora} className="grid sm:grid-cols-[90px_1fr_120px] gap-4 items-center rounded-2xl border border-slate-200 bg-white p-4"><b className="text-sm text-blue-700">{hora}</b><p className="font-black text-slate-800">{titulo}</p><span className="text-xs font-bold text-slate-400">{tipo}</span></div>)}</div></div></div></section>

      <section id="inscricao" className="mx-auto max-w-[1400px] px-5 lg:px-10 py-16"><div className="grid lg:grid-cols-[1fr_.8fr] gap-8 items-start"><div><p className="text-[11px] font-black uppercase tracking-[.22em] text-emerald-700">Inscrição demonstrativa</p><h2 className="mt-3 text-4xl lg:text-5xl font-black tracking-tight">Menos etapas. Mais conversão.</h2><p className="mt-4 max-w-2xl text-slate-500 leading-relaxed">No UVERGS 360, uma landing de evento pode ser ligada à origem da campanha para medir fonte → inscrição → presença → recorrência.</p><div className="mt-7 grid sm:grid-cols-3 gap-3">{[["Campanha","E-mail segmentado"],["Origem","Missões"],["Afinidade","96%"]].map(([a,b])=><div key={a} className="rounded-2xl bg-emerald-50 border border-emerald-100 p-4"><p className="text-[10px] font-black uppercase tracking-widest text-emerald-600">{a}</p><p className="mt-2 text-sm font-black text-emerald-950">{b}</p></div>)}</div></div>
        <div className="rounded-[32px] border border-blue-100 bg-white p-6 lg:p-8 shadow-xl shadow-blue-100/40"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-black">Pré-inscrição</p><p className="mt-1 text-xs text-slate-400">Exemplo não funcional</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-black text-blue-700">2 minutos</span></div><div className="mt-6 space-y-4"><label className="block"><span className="text-xs font-bold text-slate-500">Nome</span><div className="mt-2 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-400">Ana Martins</div></label><label className="block"><span className="text-xs font-bold text-slate-500">Câmara</span><div className="mt-2 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-400">Câmara Municipal de Santo Ângelo</div></label><label className="block"><span className="text-xs font-bold text-slate-500">E-mail</span><div className="mt-2 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-400">ana.martins@exemplo.demo</div></label></div><button className="mt-6 w-full rounded-2xl bg-blue-700 px-5 py-3.5 text-sm font-black text-white">Continuar inscrição</button><p className="mt-3 text-[10px] leading-relaxed text-slate-400">Em produção, consentimentos, preferências, finalidade e política de privacidade devem acompanhar o fluxo adequado.</p></div></div></section>

      <section className="bg-gradient-to-r from-blue-800 to-cyan-600 text-white"><div className="mx-auto max-w-[1400px] px-5 lg:px-10 py-12 flex flex-col lg:flex-row gap-6 lg:items-center lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-100">UVERGS 360</p><h2 className="mt-2 text-3xl font-black">Da campanha à presença, tudo mensurável.</h2><p className="mt-2 text-sm text-blue-100">Esta landing fecha o fluxo demonstrativo de aquisição e relacionamento.</p></div><div className="flex flex-wrap gap-3"><Link href="/admin/growth/campaigns" className="rounded-2xl bg-white px-5 py-3 text-sm font-black text-blue-800">Ver Central de Campanhas</Link><Link href="/admin/growth/journeys" className="rounded-2xl border border-white/20 bg-white/10 px-5 py-3 text-sm font-black text-white">Ver Jornadas</Link></div></div></section>
    </main>
  </div>;
}
