"use server";
import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { withAdminWrite } from "@/lib/admin-write";
import { withAdminRead } from "@/lib/admin-data";
import { collectInstitutionalSource } from "@/lib/institutional-importer";
import { isValidIsoDate } from "@/lib/financial-validation";
const ROLES=["admin_global","presidency"]; type View="camaras"|"vereadores"|"fontes"|"importacoes";
const val=(f:FormData,k:string)=>String(f.get(k)??"").trim(); const opt=(f:FormData,k:string)=>val(f,k)||null;
function done(view:View,message:string,error=false):never{revalidatePath("/admin/institucional");redirect(`/admin/institucional?view=${view}&${error?"error":"notice"}=${encodeURIComponent(message)}`)}
type Json=Parameters<ReturnType<typeof import("postgres")>["json"]>[0];
async function audit(sql:ReturnType<typeof import("postgres")>,ctx:{tenantId:string;userId:string},action:string,type:string,id:string,payload:Json){await sql`INSERT INTO audit_logs(tenant_id,user_id,correlation_id,action,module,entity_type,entity_id,new_value) VALUES(${ctx.tenantId},${ctx.userId},${randomUUID()},${action},'institutional',${type},${id},${sql.json(payload)})`}

export async function saveChamberAction(f:FormData){
 const x={id:opt(f,"id"),municipalityId:val(f,"municipalityId"),legalName:val(f,"legalName"),shortName:opt(f,"shortName"),cnpj:opt(f,"cnpj"),email:opt(f,"email"),phone:opt(f,"phone"),whatsapp:opt(f,"whatsapp"),websiteUrl:opt(f,"websiteUrl"),transparencyUrl:opt(f,"transparencyUrl"),addressLine:opt(f,"addressLine"),postalCode:opt(f,"postalCode"),status:val(f,"status"),affiliationStatus:val(f,"affiliationStatus"),affiliatedAt:opt(f,"affiliatedAt")};
 const p=z.object({id:z.string().uuid().nullable(),municipalityId:z.string().uuid(),legalName:z.string().min(3).max(200),shortName:z.string().max(80).nullable(),cnpj:z.string().max(18).nullable(),email:z.string().email().max(254).nullable(),phone:z.string().max(30).nullable(),whatsapp:z.string().max(30).nullable(),websiteUrl:z.string().url().max(1000).nullable(),transparencyUrl:z.string().url().max(1000).nullable(),addressLine:z.string().max(300).nullable(),postalCode:z.string().max(10).nullable(),status:z.enum(["active","inactive","pending"]),affiliationStatus:z.enum(["affiliated","prospect","inactive"]),affiliatedAt:z.string().nullable()}).safeParse(x);
 if(!p.success||(p.data.affiliatedAt&&!isValidIsoDate(p.data.affiliatedAt)))done("camaras","Revise os campos da Câmara.",true);
 const r=await withAdminWrite(ROLES,async(sql,ctx)=>{const d=p.data;const rows=d.id?await sql<{id:string}[]>`UPDATE chambers SET municipality_id=${d.municipalityId},legal_name=${d.legalName},short_name=${d.shortName},cnpj=${d.cnpj},email=${d.email},phone=${d.phone},whatsapp=${d.whatsapp},website_url=${d.websiteUrl},transparency_url=${d.transparencyUrl},address_line=${d.addressLine},postal_code=${d.postalCode},status=${d.status},affiliation_status=${d.affiliationStatus},affiliated_at=${d.affiliatedAt},data_quality='verified',contact_updated_at=NOW() WHERE tenant_id=${ctx.tenantId} AND id=${d.id} RETURNING id`:await sql<{id:string}[]>`INSERT INTO chambers(tenant_id,municipality_id,legal_name,short_name,cnpj,email,phone,whatsapp,website_url,transparency_url,address_line,postal_code,status,affiliation_status,affiliated_at,data_quality,contact_updated_at) VALUES(${ctx.tenantId},${d.municipalityId},${d.legalName},${d.shortName},${d.cnpj},${d.email},${d.phone},${d.whatsapp},${d.websiteUrl},${d.transparencyUrl},${d.addressLine},${d.postalCode},${d.status},${d.affiliationStatus},${d.affiliatedAt},'verified',NOW()) RETURNING id`;if(!rows[0])throw new Error("NOT_FOUND");await audit(sql,ctx,d.id?"update":"create","chamber",rows[0].id,d)});
 done("camaras",r.error??(p.data.id?"Câmara atualizada.":"Câmara cadastrada."),Boolean(r.error));
}
export async function saveMandateAction(f:FormData){
 const x={id:opt(f,"id"),personId:opt(f,"personId"),chamberId:val(f,"chamberId"),fullName:val(f,"fullName"),electoralName:opt(f,"electoralName"),email:opt(f,"email"),phone:opt(f,"phone"),whatsapp:opt(f,"whatsapp"),avatarUrl:opt(f,"avatarUrl"),office:val(f,"office"),status:val(f,"status"),electionStatus:val(f,"electionStatus"),substituteRank:opt(f,"substituteRank")?Number(val(f,"substituteRank")):null,voteCount:opt(f,"voteCount")?Number(val(f,"voteCount")):null,startedAt:val(f,"startedAt"),endedAt:opt(f,"endedAt"),legislatureLabel:opt(f,"legislatureLabel")};
 const p=z.object({id:z.string().uuid().nullable(),personId:z.string().uuid().nullable(),chamberId:z.string().uuid(),fullName:z.string().min(3).max(180),electoralName:z.string().max(120).nullable(),email:z.string().email().max(254).nullable(),phone:z.string().max(30).nullable(),whatsapp:z.string().max(30).nullable(),avatarUrl:z.string().url().max(1000).nullable(),office:z.enum(["councilor","president","vice_president","substitute"]),status:z.enum(["active","licensed","completed","revoked"]),electionStatus:z.enum(["elected","alternate","appointed","unknown"]),substituteRank:z.number().int().min(1).max(99).nullable(),voteCount:z.number().int().min(0).nullable(),startedAt:z.string().refine(isValidIsoDate),endedAt:z.string().nullable(),legislatureLabel:z.string().max(40).nullable()}).safeParse(x);
 if(!p.success||(p.data.endedAt&&!isValidIsoDate(p.data.endedAt))||(p.data.office==="substitute"&&!p.data.substituteRank))done("vereadores","Revise os dados do mandato/suplência.",true);
 const r=await withAdminWrite(ROLES,async(sql,ctx)=>{const d=p.data;let personId=d.personId;if(personId)await sql`UPDATE persons SET full_name=${d.fullName},electoral_name=${d.electoralName},email=${d.email},phone=${d.phone},whatsapp=${d.whatsapp},avatar_url=${d.avatarUrl},public_email=${Boolean(d.email)},public_phone=${Boolean(d.phone||d.whatsapp)},source_updated_at=NOW() WHERE tenant_id=${ctx.tenantId} AND id=${personId}`;else{const[pn]=await sql<{id:string}[]>`INSERT INTO persons(tenant_id,full_name,electoral_name,email,phone,whatsapp,avatar_url,public_email,public_phone,source_updated_at) VALUES(${ctx.tenantId},${d.fullName},${d.electoralName},${d.email},${d.phone},${d.whatsapp},${d.avatarUrl},${Boolean(d.email)},${Boolean(d.phone||d.whatsapp)},NOW()) RETURNING id`;personId=pn.id}const current=(d.status==="active"||d.status==="licensed")&&d.office!=="substitute";const rows=d.id?await sql<{id:string}[]>`UPDATE mandates SET chamber_id=${d.chamberId},office=${d.office},status=${d.status},election_status=${d.electionStatus},substitute_rank=${d.office==="substitute"?d.substituteRank:null},vote_count=${d.voteCount},current_exercise=${current},started_at=${d.startedAt},ended_at=${d.endedAt},legislature_label=${d.legislatureLabel} WHERE tenant_id=${ctx.tenantId} AND id=${d.id} RETURNING id`:await sql<{id:string}[]>`INSERT INTO mandates(tenant_id,person_id,chamber_id,office,status,election_status,substitute_rank,vote_count,current_exercise,started_at,ended_at,legislature_label) VALUES(${ctx.tenantId},${personId},${d.chamberId},${d.office},${d.status},${d.electionStatus},${d.office==="substitute"?d.substituteRank:null},${d.voteCount},${current},${d.startedAt},${d.endedAt},${d.legislatureLabel}) RETURNING id`;if(!rows[0])throw new Error("NOT_FOUND");await audit(sql,ctx,d.id?"update":"create","mandate",rows[0].id,d)});
 done("vereadores",r.error??(p.data.id?"Cadastro atualizado.":"Vereador/suplente cadastrado."),Boolean(r.error));
}
export async function saveSourceAction(f:FormData){
 const x={sourceType:val(f,"sourceType"),name:val(f,"name"),url:val(f,"url"),municipalityId:opt(f,"municipalityId"),chamberId:opt(f,"chamberId")};const p=z.object({sourceType:z.enum(["ibge","tse_open_data","divulgacand","chamber_portal","transparency_portal","manual"]),name:z.string().min(3).max(160),url:z.string().url().max(1000),municipalityId:z.string().uuid().nullable(),chamberId:z.string().uuid().nullable()}).safeParse(x);if(!p.success||!p.data.url.startsWith("https://"))done("fontes","Informe uma fonte HTTPS válida.",true);
 const r=await withAdminWrite(ROLES,async(sql,ctx)=>{const d=p.data;const[row]=await sql<{id:string}[]>`INSERT INTO institutional_sources(tenant_id,municipality_id,chamber_id,source_type,name,url) VALUES(${ctx.tenantId},${d.municipalityId},${d.chamberId},${d.sourceType},${d.name},${d.url}) ON CONFLICT(tenant_id,url) DO UPDATE SET name=EXCLUDED.name,source_type=EXCLUDED.source_type,municipality_id=EXCLUDED.municipality_id,chamber_id=EXCLUDED.chamber_id,active=true RETURNING id`;await audit(sql,ctx,"upsert","institutional_source",row.id,d)});done("fontes",r.error??"Fonte oficial salva.",Boolean(r.error));
}
export async function queueImportAction(f:FormData){
 const p=z.object({sourceId:z.string().uuid(),electionYear:z.number().int().min(2000).max(2200).nullable(),municipalityIbgeCode:z.string().max(10).nullable()}).safeParse({sourceId:val(f,"sourceId"),electionYear:opt(f,"electionYear")?Number(val(f,"electionYear")):null,municipalityIbgeCode:opt(f,"municipalityIbgeCode")});if(!p.success)done("importacoes","Revise os parâmetros.",true);
 const r=await withAdminWrite(ROLES,async(sql,ctx)=>{const[row]=await sql<{id:string}[]>`INSERT INTO institutional_imports(tenant_id,source_id,requested_by,election_year,municipality_ibge_code) SELECT ${ctx.tenantId},id,${ctx.userId},${p.data.electionYear},${p.data.municipalityIbgeCode} FROM institutional_sources WHERE tenant_id=${ctx.tenantId} AND id=${p.data.sourceId} AND active RETURNING id`;if(!row)throw new Error("SOURCE_NOT_FOUND");await audit(sql,ctx,"queue","institutional_import",row.id,p.data)});done("importacoes",r.error??"Importação colocada na fila.",Boolean(r.error));
}
export async function processImportAction(f:FormData){
 const id=val(f,"id");if(!z.string().uuid().safeParse(id).success)done("importacoes","Importação inválida.",true);
 const found=await withAdminRead(ROLES,async sql=>{const[r]=await sql<{id:string;url:string;sourceType:string;chamberId:string|null;municipalityId:string|null;municipalityIbgeCode:string|null}[]>`SELECT i.id,s.url,s.source_type AS "sourceType",s.chamber_id AS "chamberId",s.municipality_id AS "municipalityId",i.municipality_ibge_code AS "municipalityIbgeCode" FROM institutional_imports i JOIN institutional_sources s ON s.id=i.source_id AND s.tenant_id=i.tenant_id WHERE i.id=${id} AND i.status IN ('queued','failed')`;return r??null});
 if(!found.data)done("importacoes",found.error??"Importação não encontrada.",true);
 try{const proposals=await collectInstitutionalSource(found.data);const r=await withAdminWrite(ROLES,async(sql,ctx)=>{await sql`DELETE FROM institutional_import_items WHERE tenant_id=${ctx.tenantId} AND import_id=${id}`;for(const item of proposals)await sql`INSERT INTO institutional_import_items(tenant_id,import_id,entity_type,external_id,operation,confidence,source_payload,proposed_data) VALUES(${ctx.tenantId},${id},${item.entityType},${item.externalId},${item.operation},${item.confidence},${sql.json(item.sourcePayload)},${sql.json(item.proposedData)})`;await sql`UPDATE institutional_imports SET status='review',total_items=${proposals.length},started_at=COALESCE(started_at,NOW()),finished_at=NOW(),error_message=NULL WHERE tenant_id=${ctx.tenantId} AND id=${id}`;await sql`UPDATE institutional_sources SET last_checked_at=NOW(),last_success_at=NOW(),last_error=NULL WHERE tenant_id=${ctx.tenantId} AND id=(SELECT source_id FROM institutional_imports WHERE id=${id} AND tenant_id=${ctx.tenantId})`});done("importacoes",r.error??String(proposals.length)+" itens coletados para revisão.",Boolean(r.error))}
 catch(error){const message=error instanceof Error?error.message:"Falha na coleta";await withAdminWrite(ROLES,async(sql,ctx)=>{await sql`UPDATE institutional_imports SET status='failed',finished_at=NOW(),error_message=LEFT(${message},500) WHERE tenant_id=${ctx.tenantId} AND id=${id}`});done("importacoes","A fonte não pôde ser processada: "+message,true)}
}
