import Link from "next/link";
import { loadInstitutionalWorkspace } from "@/lib/institutional-data";
import { DataNotice } from "../_components/DataNotice";
import { processImportAction,queueImportAction,saveChamberAction,saveMandateAction,saveSourceAction } from "./actions";
const VIEWS=[["camaras","Câmaras"],["vereadores","Vereadores e suplentes"],["fontes","Fontes oficiais"],["importacoes","Importações"]] as const;
const input="modern-input"; type View=(typeof VIEWS)[number][0];
function F({name,label,type="text",value}:{name:string;label:string;type?:string;value?:string|null}){return <label><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span><input name={name} type={type} defaultValue={value??""} className={input}/></label>}
export default async function Page({searchParams}:{searchParams:Promise<{view?:string;editChamber?:string;editMandate?:string;notice?:string;error?:string}>}){
 const p=await searchParams,view=(VIEWS.some(([v])=>v===p.view)?p.view:"camaras") as View,r=await loadInstitutionalWorkspace(),d=r.data,c=d?.chambers.find(x=>x.id===p.editChamber),m=d?.mandates.find(x=>x.id===p.editMandate);
 return <div className="page-canvas"><section className="relative overflow-hidden rounded-[28px] bg-gradient-to-br from-[#073b78] via-[#087ca7] to-[#19a78c] px-6 py-8 text-white shadow-xl sm:px-9"><span className="eyebrow-light">Rede UVERGS</span><h1 className="mt-3 text-3xl font-semibold sm:text-4xl">Câmaras, mandatos e relacionamento.</h1><p className="mt-3 max-w-3xl text-sm text-cyan-50">Cadastro completo de Câmaras, vereadores e até o terceiro suplente, com contatos e fontes oficiais rastreáveis.</p></section>
 {r.error&&<div className="mt-6"><DataNotice message={r.error}/></div>}{p.notice&&<div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{p.notice}</div>}{p.error&&<div className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{p.error}</div>}
 {d&&<><section className="metric-grid mt-6">{[["Câmaras",d.totals.chambers,"blue"],["Associadas",d.totals.affiliated,"green"],["Vereadores",d.totals.councilors,"violet"],["Suplentes 1º–3º",d.totals.substitutes,"gold"],["Sem contato",d.totals.missingContacts,"red"],["Importações",d.totals.pendingImports,"blue"]].map(([l,v,t])=><article className={"metric-card metric-"+t} key={String(l)}><p className="text-xs uppercase tracking-wider text-slate-500">{l}</p><p className="mt-3 text-3xl font-semibold">{v}</p></article>)}</section>
 <nav className="mt-6 flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2">{VIEWS.map(([v,l])=><Link key={v} href={"/admin/institucional?view="+v} className={"whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-semibold "+(view===v?"bg-[#0b4b7e] text-white":"text-slate-500")}>{l}</Link>)}</nav>

 {view==="camaras"&&<div className="mt-6 space-y-6"><form action={saveChamberAction} className="surface-panel p-6"><input type="hidden" name="id" value={c?.id??""}/><h2 className="text-xl font-semibold">{c?"Editar Câmara":"Cadastrar Câmara"}</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
 <label><span className="mb-1.5 block text-xs font-semibold text-slate-600">Município *</span><select name="municipalityId" defaultValue={c?.municipalityId} className={input} required><option value="">Selecione</option>{d.municipalities.map(x=><option key={x.id} value={x.id}>{x.name}/{x.stateCode}</option>)}</select></label>
 <F name="legalName" label="Nome oficial *" value={c?.legalName}/><F name="shortName" label="Nome curto" value={c?.shortName}/><F name="cnpj" label="CNPJ" value={c?.cnpj}/><F name="email" label="E-mail institucional" type="email" value={c?.email}/><F name="phone" label="Telefone" value={c?.phone}/><F name="whatsapp" label="WhatsApp" value={c?.whatsapp}/><F name="postalCode" label="CEP" value={c?.postalCode}/><F name="websiteUrl" label="Site oficial" type="url" value={c?.websiteUrl}/><F name="transparencyUrl" label="Portal da Transparência" type="url" value={c?.transparencyUrl}/><F name="addressLine" label="Endereço" value={c?.addressLine}/>
 <label><span className="mb-1.5 block text-xs font-semibold text-slate-600">Situação</span><select name="status" defaultValue={c?.status??"active"} className={input}><option value="active">Ativa</option><option value="pending">Pendente</option><option value="inactive">Inativa</option></select></label><label><span className="mb-1.5 block text-xs font-semibold text-slate-600">Vínculo UVERGS</span><select name="affiliationStatus" defaultValue={c?.affiliationStatus??"prospect"} className={input}><option value="prospect">Em relacionamento</option><option value="affiliated">Associada</option><option value="inactive">Inativa</option></select></label><F name="affiliatedAt" label="Associada desde" type="date" value={c?.affiliatedAt}/>
 </div><button className="primary-button mt-5">{c?"Salvar alterações":"Cadastrar Câmara"}</button></form><List title="Diretório de Câmaras">{d.chambers.map(x=><article key={x.id} className="grid gap-3 p-5 lg:grid-cols-[1fr_.6fr_auto] lg:items-center"><div><p className="font-semibold">{x.shortName??x.legalName}</p><p className="text-sm text-slate-500">{x.municipality} · {x.email??"sem e-mail"} · {x.phone??x.whatsapp??"sem telefone"}</p></div><p className="text-sm">{x.councilors} titulares · {x.substitutes}/3 suplentes</p><Link className="rounded-xl bg-blue-50 px-3 py-2 text-center text-xs font-semibold text-blue-700" href={"/admin/institucional?view=camaras&editChamber="+x.id}>Editar</Link></article>)}</List></div>}

 {view==="vereadores"&&<div className="mt-6 space-y-6"><form action={saveMandateAction} className="surface-panel p-6"><input type="hidden" name="id" value={m?.id??""}/><input type="hidden" name="personId" value={m?.personId??""}/><h2 className="text-xl font-semibold">{m?"Editar vereador/suplente":"Cadastrar vereador ou suplente"}</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
 <label><span className="mb-1.5 block text-xs font-semibold text-slate-600">Câmara *</span><select name="chamberId" defaultValue={m?.chamberId} className={input} required><option value="">Selecione</option>{d.chambers.map(x=><option key={x.id} value={x.id}>{x.municipality} — {x.shortName??x.legalName}</option>)}</select></label><F name="fullName" label="Nome completo *" value={m?.fullName}/><F name="electoralName" label="Nome eleitoral" value={m?.electoralName}/>
 <label><span className="mb-1.5 block text-xs font-semibold text-slate-600">Cargo</span><select name="office" defaultValue={m?.office??"councilor"} className={input}><option value="councilor">Vereador</option><option value="president">Presidente</option><option value="vice_president">Vice-presidente</option><option value="substitute">Suplente</option></select></label><F name="email" label="E-mail público" type="email" value={m?.email}/><F name="phone" label="Telefone público" value={m?.phone}/><F name="whatsapp" label="WhatsApp público" value={m?.whatsapp}/><F name="avatarUrl" label="URL da foto" type="url" value={m?.avatarUrl}/>
 <label><span className="mb-1.5 block text-xs font-semibold text-slate-600">Situação</span><select name="status" defaultValue={m?.status??"active"} className={input}><option value="active">Ativo</option><option value="licensed">Licenciado</option><option value="completed">Encerrado</option><option value="revoked">Revogado</option></select></label><label><span className="mb-1.5 block text-xs font-semibold text-slate-600">Resultado</span><select name="electionStatus" defaultValue={m?.electionStatus??"elected"} className={input}><option value="elected">Eleito</option><option value="alternate">Suplente</option><option value="appointed">Empossado</option><option value="unknown">Não confirmado</option></select></label><F name="substituteRank" label="Posição de suplência" type="number" value={m?.substituteRank?String(m.substituteRank):""}/><F name="voteCount" label="Votos" type="number" value={m?.voteCount?String(m.voteCount):""}/><F name="startedAt" label="Início *" type="date" value={m?.startedAt??"2025-01-01"}/><F name="endedAt" label="Término" type="date" value={m?.endedAt}/><F name="legislatureLabel" label="Legislatura" value={m?.legislatureLabel??"2025–2028"}/>
 </div><button className="primary-button mt-5">{m?"Salvar alterações":"Cadastrar mandato"}</button></form><List title="Vereadores e suplentes">{d.mandates.map(x=><article key={x.id} className="grid gap-3 p-5 lg:grid-cols-[1fr_.7fr_.4fr_auto] lg:items-center"><div><p className="font-semibold">{x.electoralName??x.fullName}</p><p className="text-sm text-slate-500">{x.email??"sem e-mail"} · {x.phone??x.whatsapp??"sem telefone"}</p></div><p className="text-sm">{x.municipality}</p><p className="font-semibold">{x.office==="substitute"?String(x.substituteRank)+"º suplente":"Vereador"}</p><Link className="rounded-xl bg-blue-50 px-3 py-2 text-center text-xs font-semibold text-blue-700" href={"/admin/institucional?view=vereadores&editMandate="+x.id}>Editar</Link></article>)}</List></div>}

 {view==="fontes"&&<div className="mt-6 grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form action={saveSourceAction} className="surface-panel p-6"><h2 className="text-xl font-semibold">Adicionar fonte oficial</h2><div className="mt-5 space-y-4"><label><span className="mb-1.5 block text-xs font-semibold">Tipo</span><select name="sourceType" className={input}><option value="chamber_portal">Portal da Câmara</option><option value="transparency_portal">Portal da Transparência</option><option value="tse_open_data">Dados Abertos TSE</option><option value="divulgacand">DivulgaCand</option><option value="ibge">IBGE</option></select></label><F name="name" label="Nome *"/><F name="url" label="URL oficial HTTPS *" type="url"/><label><span className="mb-1.5 block text-xs font-semibold">Município</span><select name="municipalityId" className={input}><option value="">Fonte geral</option>{d.municipalities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span className="mb-1.5 block text-xs font-semibold">Câmara</span><select name="chamberId" className={input}><option value="">Não vinculada</option>{d.chambers.map(x=><option key={x.id} value={x.id}>{x.municipality}</option>)}</select></label><button className="primary-button w-full">Salvar fonte</button></div></form><List title="Fontes cadastradas">{d.sources.map(x=><article className="p-5" key={x.id}><p className="font-semibold">{x.name}</p><p className="text-xs text-slate-500">{x.municipality??"Abrangência geral"} · {x.sourceType}</p><a className="block truncate text-sm text-blue-700" href={x.url} target="_blank" rel="noreferrer">{x.url}</a></article>)}</List></div>}

 {view==="importacoes"&&<div className="mt-6 grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form action={queueImportAction} className="surface-panel p-6"><h2 className="text-xl font-semibold">Nova importação</h2><p className="mt-2 text-sm text-slate-500">A coleta prepara sugestões para revisão; nunca sobrescreve dados confirmados.</p><div className="mt-5 space-y-4"><label><span className="mb-1.5 block text-xs font-semibold">Fonte *</span><select name="sourceId" className={input} required><option value="">Selecione</option>{d.sources.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><F name="electionYear" label="Ano da eleição" type="number" value="2024"/><F name="municipalityIbgeCode" label="Código IBGE/TSE do município"/><button className="primary-button w-full">Criar importação</button></div></form><List title="Fila e histórico">{d.imports.map(x=><article className="grid gap-3 p-5 sm:grid-cols-[1fr_auto] sm:items-center" key={x.id}><div><p className="font-semibold">{x.sourceName}</p><p className="text-xs text-slate-500">{x.status} · {x.totalItems} itens · {new Date(x.createdAt).toLocaleString("pt-BR")}</p></div>{(x.status==="queued"||x.status==="failed")&&<form action={processImportAction}><input type="hidden" name="id" value={x.id}/><button className="rounded-xl bg-emerald-50 px-4 py-2 text-xs font-semibold text-emerald-700">Processar agora</button></form>}</article>)}</List></div>}
 </>}</div>
}
function List({title,children}:{title:string;children:React.ReactNode}){return <section className="surface-panel overflow-hidden"><header className="border-b p-6"><h2 className="text-xl font-semibold">{title}</h2></header><div className="divide-y">{children}</div></section>}
