"use client";

import type { BankEntryRow, BudgetExecutionRow, TransactionOption } from "@/lib/financial-data";

import { createBudgetLineAction, createStatementEntryAction, ignoreStatementEntryAction, matchStatementEntryAction } from "../actions";
import { currency } from "./FinancePanels";

const inputClass = "form-input";

export function BudgetPanel({ data }: { data: BudgetExecutionRow[] }) {
  return <div className="space-y-6"><form action={createBudgetLineAction} className="surface-panel p-6"><span className="eyebrow">Planejamento</span><h2 className="mt-1 text-xl font-semibold text-slate-950">Adicionar linha ao orçamento aprovado</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Input label="Ano"><input className={inputClass} name="year" type="number" min="2020" max="2200" defaultValue={new Date().getFullYear()} required /></Input><Input label="Mês"><input className={inputClass} name="month" type="number" min="1" max="12" required /></Input><Input label="Natureza"><select className={inputClass} name="nature"><option value="revenue">Receita</option><option value="expense">Despesa</option></select></Input><Input label="Categoria"><input className={inputClass} name="category" minLength={2} maxLength={80} required placeholder="Ex.: Capacitação" /></Input><Input label="Valor planejado"><input className={inputClass} name="amount" inputMode="decimal" required placeholder="0,00" /></Input></div><div className="mt-5 flex justify-end"><button className="rounded-xl bg-[#0b4b7e] px-5 py-3 text-sm font-semibold text-white">Adicionar ao orçamento</button></div></form><section className="surface-panel overflow-hidden"><header className="border-b border-slate-200 p-6"><span className="eyebrow">Execução real</span><h2 className="mt-1 text-xl font-semibold">Orçado x realizado</h2></header><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="p-4">Período</th><th className="p-4">Conta</th><th className="p-4">Centro</th><th className="p-4">Planejado</th><th className="p-4">Realizado</th></tr></thead><tbody>{data.map((row,index)=><tr className="border-t border-slate-100" key={`${row.year}-${row.month}-${row.accountName}-${index}`}><td className="p-4">{String(row.month).padStart(2,"0")}/{row.year}</td><td className="p-4 font-medium">{row.accountName}</td><td className="p-4">{row.costCenterName}</td><td className="p-4">{currency(row.plannedCents)}</td><td className="p-4">{currency(row.actualCents)}</td></tr>)}</tbody></table></div></section></div>;
}

export function ReconciliationPanel({ entries, transactions }: { entries: BankEntryRow[]; transactions: TransactionOption[] }) {
  return <div className="space-y-6"><form action={createStatementEntryAction} className="surface-panel p-6"><span className="eyebrow">Extrato</span><h2 className="mt-1 text-xl font-semibold">Importar lançamento bancário manual</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Input label="Data"><input className={inputClass} name="postedAt" type="date" required /></Input><Input label="Tipo"><select className={inputClass} name="direction"><option value="inflow">Entrada</option><option value="outflow">Saída</option></select></Input><Input label="Descrição"><input className={inputClass} name="description" required minLength={3} /></Input><Input label="Valor"><input className={inputClass} name="amount" inputMode="decimal" required placeholder="0,00" /></Input></div><div className="mt-5 flex justify-end"><button className="rounded-xl bg-[#0b4b7e] px-5 py-3 text-sm font-semibold text-white">Adicionar ao extrato</button></div></form><section className="surface-panel overflow-hidden"><header className="border-b border-slate-200 p-6"><span className="eyebrow">Conciliação</span><h2 className="mt-1 text-xl font-semibold">Pendências bancárias</h2></header><div className="divide-y divide-slate-100">{entries.map(entry=><article key={entry.id} className="grid gap-3 p-5 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="font-semibold text-slate-900">{entry.description}</p><p className="mt-1 text-xs text-slate-400">{new Date(entry.postedAt).toLocaleDateString("pt-BR",{timeZone:"UTC"})} · {currency(entry.amountCents)}</p></div>{entry.status === "unmatched" ? <div className="flex flex-wrap gap-2"><form action={matchStatementEntryAction} className="flex gap-2"><input type="hidden" name="entryId" value={entry.id} /><select name="transactionId" className="form-input min-w-52" required><option value="">Selecionar movimentação</option>{transactions.filter(tx=>tx.amountCents===Math.abs(entry.amountCents)).map(tx=><option key={tx.id} value={tx.id}>{tx.memo ?? tx.type} · {currency(tx.amountCents)}</option>)}</select><button className="rounded-xl bg-emerald-50 px-3 text-xs font-semibold text-emerald-700">Conciliar</button></form><form action={ignoreStatementEntryAction}><input type="hidden" name="entryId" value={entry.id} /><button className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-500">Ignorar</button></form></div> : <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">{entry.status === "matched" ? "Conciliado" : "Ignorado"}</span>}</article>)}</div></section></div>;
}

function Input({ label, children }: { label: string; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label} *</span>{children}</label>; }
