import { withAdminRead, type AdminDataResult } from "./admin-data";
const ROLES=["admin_global","presidency","audit_read"];
export interface MunicipalityOption{id:string;ibgeCode:string;name:string;stateCode:string}
export interface ChamberRecord{id:string;municipalityId:string;municipality:string;ibgeCode:string;legalName:string;shortName:string|null;cnpj:string|null;email:string|null;phone:string|null;whatsapp:string|null;websiteUrl:string|null;transparencyUrl:string|null;addressLine:string|null;postalCode:string|null;status:string;affiliationStatus:string;affiliatedAt:string|null;dataQuality:string;councilors:number;substitutes:number}
export interface MandateRecord{id:string;personId:string;chamberId:string;chamberName:string;municipality:string;fullName:string;electoralName:string|null;email:string|null;phone:string|null;whatsapp:string|null;avatarUrl:string|null;office:string;status:string;electionStatus:string|null;substituteRank:number|null;voteCount:number|null;startedAt:string;endedAt:string|null;legislatureLabel:string|null}
export interface SourceRecord{id:string;chamberId:string|null;municipalityId:string|null;municipality:string|null;sourceType:string;name:string;url:string;active:boolean;lastCheckedAt:Date|null;lastSuccessAt:Date|null;lastError:string|null}
export interface ImportRecord{id:string;sourceName:string;status:string;electionYear:number|null;municipalityIbgeCode:string|null;totalItems:number;createdAt:Date}
export interface InstitutionalWorkspace{municipalities:MunicipalityOption[];chambers:ChamberRecord[];mandates:MandateRecord[];sources:SourceRecord[];imports:ImportRecord[];totals:{chambers:number;affiliated:number;councilors:number;substitutes:number;missingContacts:number;pendingImports:number}}
export async function loadInstitutionalWorkspace():Promise<AdminDataResult<InstitutionalWorkspace>>{
 return withAdminRead(ROLES,async sql=>{
  const [municipalities,chambers,mandates,sources,imports,totals]=await Promise.all([
   sql<MunicipalityOption[]>`SELECT id,ibge_code AS "ibgeCode",name,state_code AS "stateCode" FROM public_ref.municipalities WHERE active AND state_code='RS' ORDER BY name`,
   sql<ChamberRecord[]>`SELECT c.id,c.municipality_id AS "municipalityId",m.name AS municipality,m.ibge_code AS "ibgeCode",c.legal_name AS "legalName",c.short_name AS "shortName",c.cnpj,c.email,c.phone,c.whatsapp,c.website_url AS "websiteUrl",c.transparency_url AS "transparencyUrl",c.address_line AS "addressLine",c.postal_code AS "postalCode",c.status,c.affiliation_status AS "affiliationStatus",c.affiliated_at::text AS "affiliatedAt",c.data_quality AS "dataQuality",COUNT(md.id) FILTER(WHERE md.office<>'substitute' AND md.status IN ('active','licensed'))::int councilors,COUNT(md.id) FILTER(WHERE md.office='substitute' AND md.substitute_rank<=3)::int substitutes FROM chambers c JOIN public_ref.municipalities m ON m.id=c.municipality_id LEFT JOIN mandates md ON md.tenant_id=c.tenant_id AND md.chamber_id=c.id GROUP BY c.id,m.id ORDER BY m.name`,
   sql<MandateRecord[]>`SELECT md.id,md.person_id AS "personId",md.chamber_id AS "chamberId",COALESCE(c.short_name,c.legal_name) AS "chamberName",mu.name AS municipality,p.full_name AS "fullName",p.electoral_name AS "electoralName",p.email,p.phone,p.whatsapp,p.avatar_url AS "avatarUrl",md.office,md.status,md.election_status AS "electionStatus",md.substitute_rank AS "substituteRank",md.vote_count AS "voteCount",md.started_at::text AS "startedAt",md.ended_at::text AS "endedAt",md.legislature_label AS "legislatureLabel" FROM mandates md JOIN persons p ON p.id=md.person_id AND p.tenant_id=md.tenant_id JOIN chambers c ON c.id=md.chamber_id AND c.tenant_id=md.tenant_id JOIN public_ref.municipalities mu ON mu.id=c.municipality_id WHERE p.deleted_at IS NULL ORDER BY mu.name,md.substitute_rank NULLS FIRST,p.full_name`,
   sql<SourceRecord[]>`SELECT s.id,s.chamber_id AS "chamberId",s.municipality_id AS "municipalityId",m.name municipality,s.source_type AS "sourceType",s.name,s.url,s.active,s.last_checked_at AS "lastCheckedAt",s.last_success_at AS "lastSuccessAt",s.last_error AS "lastError" FROM institutional_sources s LEFT JOIN public_ref.municipalities m ON m.id=s.municipality_id ORDER BY s.active DESC,s.name`,
   sql<ImportRecord[]>`SELECT i.id,s.name AS "sourceName",i.status,i.election_year AS "electionYear",i.municipality_ibge_code AS "municipalityIbgeCode",i.total_items AS "totalItems",i.created_at AS "createdAt" FROM institutional_imports i JOIN institutional_sources s ON s.id=i.source_id ORDER BY i.created_at DESC LIMIT 50`,
   sql<InstitutionalWorkspace["totals"][]>`SELECT (SELECT COUNT(*)::int FROM chambers) chambers,(SELECT COUNT(*)::int FROM chambers WHERE affiliation_status='affiliated') affiliated,(SELECT COUNT(*)::int FROM mandates WHERE office<>'substitute' AND status IN ('active','licensed')) councilors,(SELECT COUNT(*)::int FROM mandates WHERE office='substitute' AND substitute_rank<=3) substitutes,(SELECT COUNT(*)::int FROM persons p WHERE p.deleted_at IS NULL AND COALESCE(p.email,'')='' AND COALESCE(p.phone,'')='' AND COALESCE(p.whatsapp,'')='') AS "missingContacts",(SELECT COUNT(*)::int FROM institutional_imports WHERE status IN ('queued','processing','review')) AS "pendingImports"`
  ]);
  return{municipalities,chambers,mandates,sources,imports,totals:totals[0]??{chambers:0,affiliated:0,councilors:0,substitutes:0,missingContacts:0,pendingImports:0}};
 });
}
