import { isIP } from "node:net";
import { lookup } from "node:dns/promises";

export interface ImportSource {url:string;sourceType:string;chamberId:string|null;municipalityId:string|null;municipalityIbgeCode:string|null}
export interface ImportProposal {entityType:"chamber"|"person"|"mandate"|"contact";externalId:string|null;operation:"create"|"update"|"conflict"|"unchanged";confidence:number;sourcePayload:Record<string,string|number|null>;proposedData:Record<string,string|number|null>}
const officialHosts=["tse.jus.br","ibge.gov.br","gov.br","leg.br"];
function privateIp(address:string){if(address==="::1"||address.startsWith("fc")||address.startsWith("fd")||address.startsWith("fe80:"))return true;if(isIP(address)!==4)return false;const p=address.split(".").map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)||p[0]>=224}
async function checkedUrl(raw:string){const url=new URL(raw);if(url.protocol!=="https:"||url.username||url.password||(url.port&&url.port!=="443"))throw new Error("Somente fontes oficiais HTTPS são permitidas");const host=url.hostname.toLowerCase();if(!officialHosts.some(s=>host===s||host.endsWith("."+s)))throw new Error("O domínio informado não é governamental ou legislativo");const addresses=await lookup(host,{all:true});if(!addresses.length||addresses.some(x=>privateIp(x.address)))throw new Error("Endereço de rede da fonte não permitido");return url}
async function safeFetch(raw:string){let url=await checkedUrl(raw);for(let i=0;i<4;i++){const response=await fetch(url,{redirect:"manual",signal:AbortSignal.timeout(15000),headers:{"user-agent":"UVERGS360/1.0 institutional-directory"}});if(response.status>=300&&response.status<400){const next=response.headers.get("location");if(!next)throw new Error("Redirecionamento inválido");url=await checkedUrl(new URL(next,url).toString());continue}if(!response.ok)throw new Error("Fonte respondeu HTTP "+response.status);const length=Number(response.headers.get("content-length")??0);if(length>8_000_000)throw new Error("Arquivo maior que 8 MB; use um recorte municipal");const text=await response.text();if(text.length>8_000_000)throw new Error("Conteúdo maior que 8 MB");return{text,contentType:response.headers.get("content-type")??""}}throw new Error("Excesso de redirecionamentos")}
function cleanHtml(text:string){return text.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/\s+/g," ")}
function portalProposals(source:ImportSource,text:string):ImportProposal[]{const body=cleanHtml(text);const emails=[...new Set((body.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)??[]).map(x=>x.toLowerCase()))].slice(0,20);const phones=[...new Set((body.match(/(?:\+?55\s*)?(?:\(?\d{2}\)?\s*)?(?:9\s*)?\d{4}[-.\s]?\d{4}/g)??[]).map(x=>x.trim()))].slice(0,20);if(!emails.length&&!phones.length)return[];return[{entityType:"contact",externalId:source.chamberId,operation:"update",confidence:70,sourcePayload:{url:source.url},proposedData:{emails:emails.join("; "),phones:phones.join("; ")}}]}
function parseCsvLine(line:string,delimiter:string){const out:string[]=[];let value="",quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){value+='"';i++}else quoted=!quoted}else if(c===delimiter&&!quoted){out.push(value);value=""}else value+=c}out.push(value);return out}
function tseProposals(source:ImportSource,text:string):ImportProposal[]{const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const delimiter=lines[0].includes(";")?";":",";const headers=parseCsvLine(lines[0],delimiter).map(x=>x.replace(/^"|"$/g,"").trim());const get=(row:string[],...names:string[])=>{const i=headers.findIndex(h=>names.includes(h));return i>=0?(row[i]??"").replace(/^"|"$/g,"").trim():""};const candidates=new Map<string,{fullName:string;electoralName:string;party:string;votes:number;externalId:string;status:string}>();for(const line of lines.slice(1,100001)){const row=parseCsvLine(line,delimiter);if(!get(row,"DS_CARGO","NM_CARGO").toUpperCase().includes("VEREADOR"))continue;const situation=get(row,"DS_SIT_TOT_TURNO","DS_SITUACAO_CANDIDATURA").toUpperCase();if(!situation.includes("ELEITO")&&!situation.includes("SUPLENTE"))continue;const municipality=get(row,"CD_MUNICIPIO","CD_MUN_TSE","SG_UE");if(source.municipalityIbgeCode&&municipality&&municipality!==source.municipalityIbgeCode)continue;const id=get(row,"SQ_CANDIDATO","NR_CANDIDATO")||get(row,"NM_CANDIDATO");const votes=Number(get(row,"QT_VOTOS_NOMINAIS_VALIDOS","QT_VOTOS_NOMINAIS","QT_VOTOS"))||0;const current=candidates.get(id);if(!current||votes>current.votes)candidates.set(id,{fullName:get(row,"NM_CANDIDATO"),electoralName:get(row,"NM_URNA_CANDIDATO"),party:get(row,"SG_PARTIDO"),votes,externalId:id,status:situation})}const selected=[...candidates.values()];const substitutes=selected.filter(x=>x.status.includes("SUPLENTE")).sort((a,b)=>b.votes-a.votes).slice(0,3);const ranks=new Map(substitutes.map((x,i)=>[x.externalId,i+1]));return selected.filter(x=>!x.status.includes("SUPLENTE")||ranks.has(x.externalId)).map(x=>({entityType:"mandate",externalId:x.externalId,operation:"create",confidence:85,sourcePayload:{url:source.url,rawStatus:x.status},proposedData:{fullName:x.fullName,electoralName:x.electoralName,party:x.party,voteCount:x.votes,electionStatus:x.status.includes("SUPLENTE")?"alternate":"elected",office:x.status.includes("SUPLENTE")?"substitute":"councilor",substituteRank:ranks.get(x.externalId)??null}}))}
export async function collectInstitutionalSource(source:ImportSource):Promise<ImportProposal[]>{const {text,contentType}=await safeFetch(source.url);if(source.sourceType==="tse_open_data"||source.sourceType==="divulgacand"||contentType.includes("csv"))return tseProposals(source,text);if(source.sourceType==="ibge"){const parsed=JSON.parse(text) as {id?:number;nome?:string};return[{entityType:"chamber",externalId:String(parsed.id??source.municipalityIbgeCode??""),operation:"unchanged",confidence:100,sourcePayload:{url:source.url},proposedData:{municipality:parsed.nome??null,ibgeCode:parsed.id??null}}]}return portalProposals(source,text)}
